### ISSUE TITLE
installation failed because of Cannot find a resource for mysql_database

### ISSUE THREAD

**Issue by chaoranxie** [chef/django-quick-start#1]
hi Opscode, 

i am trying to run the tutorial using the following command

knife bootstrap 107.22.24.180 -i ~/.ssh/django-quick-start.pem -x ubuntu       -r 'role[base],role[django_cms_database_master],role[django_cms],recipe[django_cms::db_bootstrap],role[django_cms_load_balancer]' --sudo

but i am getting the following error  "Cannot find a resource for mysql_database"  i know that the tutorial uses chef-client 0.10.0 but i dont think that's available anymore.

i tried to use  --bootstrap-version 10.12.0   and 11.0.0.alpha both are giving me the same error. Hope you can help me out.

Relevant File Content:
107.22.24.180 ----------------------
107.22.24.180 /var/chef/cache/cookbooks/database/recipes/master.rb:
107.22.24.180
107.22.24.180  77:  end
107.22.24.180  78:
107.22.24.180  79:  search(:apps) do |app|
107.22.24.180  80:    (app['database_master_role'] & node.run_list.roles).each do |dbm_role|
107.22.24.180  81:      app['databases'].each do |env,db|
107.22.24.180  82:        if env =~ /#{node.chef_environment}/
107.22.24.180  83:          root_pw = node['mysql']['server_root_password']
107.22.24.180  84>>         mysql_database "create #{db['database']}" do
107.22.24.180  85:            host "localhost"
107.22.24.180  86:            username "root"
107.22.24.180  87:            password root_pw
107.22.24.180  88:            database db['database']
107.22.24.180  89:            action [:create_db]
107.22.24.180  90:          end
107.22.24.180  91:        end
107.22.24.180  92:      end
107.22.24.180  93:    end
107.22.24.180
107.22.24.180
107.22.24.180
107.22.24.180 [2012-12-26T01:33:44+00:00] ERROR: Running exception handlers
107.22.24.180 [2012-12-26T01:33:44+00:00] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
107.22.24.180 [2012-12-26T01:33:44+00:00] ERROR: Exception handlers complete
107.22.24.180 Chef Client failed. 1 resources updated
107.22.24.180 [2012-12-26T01:33:44+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
107.22.24.180 [2012-12-26T01:33:44+00:00] FATAL: NameError: Cannot find a resource for mysql_database on ubuntu version 10.04

**Comment by chaoranxie** [comment]
Note that i dont see any resource/provider listed in the mysql or database cookbook under django-quick start.  but i am not sure if there was other way to include resource/provider. i do see a library file under mysql.
https://github.com/opscode/django-quick-start/blob/master/cookbooks/mysql/libraries/database.rb

**Comment by tas50** [comment]
Closing as this repository has been deprecated
